### PR TITLE
Update collaborators/repo counter

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by zilchms — APPROVED** [review]
Isnt that something we could automate somehow? ^^

**Comment by bastelfreak** [comment]
We had (or still have?) javascript in place that pulls it live from GitHub. But now that only works if you'red logged into GitHub :(

It would be nice to have some automation to update the site.

**Comment by zilchms** [comment]
building that as a workflow / periodic bot here? might be an idea

**Comment by bastelfreak** [comment]
I'm happy to review your PR!

**Pull request merged**
