### PR TITLE
update license to CC-BY-SA 4.0

### PR DESCRIPTION
**Pull request by bastelfreak**
@alexjfisher @dhollinger I need some feedback here :)

### CODE REVIEW

**Comment by dhollinger** [comment]
We may need both a source code license and a content license for this since it contains both content and source code.

**Comment by bastelfreak** [comment]
ugh :D I forwarded that question to the Software Freedom Conservancy. I would then vote for Apache-2 + CC-BY-SA 4.0

**Comment by bastelfreak** [comment]
@dhollinger @dhollinger can you have a look please? SFC suggested that we need two licenses, one for our code and one for our content. I would like to stay with the apache-2 license for our code and CC-BY-SA 4 for the content. We already use that for our logos at https://github.com/voxpupuli/logos#voxpupuli-logos.

**Comment by bastelfreak** [comment]
@alexjfisher ^

**Comment by bastelfreak** [comment]
Hey @binford2k @nibalizer @daenney @rnelson0 @igalic @roidelapluie you are the main contributors to content on this website (besides @dhollinger and myself). Are you okay if we license your content with the CC-BY-SA 4 license? Having an explicit license for the content is the last requirement we have to fulfill to be part of the Software Freedom Conservancy \o/

**Comment by igalic** [comment]
+1 from me

**Comment by daenney** [comment]
:shipit:

**Comment by roidelapluie** [comment]
I accept

**Comment by rnelson0** [comment]
I accept.

**Comment by nibalizer** [comment]
Go for it! (And I miss you all dearly!)

**Comment by bastelfreak** [comment]
\o/

**Pull request merged**
